; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
platform_packages = toolchain-gccarmnoneeabi@~1.120301.0

; NOTE: just edit this if we want to upload a different script
build_src_filter =
    -<*>
    +<experiments/005servoJerkyHypothesis.cpp>

; Add the FreeRTOS library dependency
lib_deps = 
    stm32duino/STM32duino FreeRTOS
; Common upload protocol for the Blue Pill (change if using serial/dfu)
upload_protocol = stlink



